server:
  port : 8443
spring:
  datasource:
    url: jdbc:mysql://119.29.79.210:3306/blog?characterEncoding=UTF-8&useSSL=false
#    url: jdbc:log4jdbc:mysql://119.29.79.210:3306/blog?characterEncoding=UTF-8&useSSL=false
    username: root
    password: redhat
    driver-class-name: com.mysql.jdbc.Driver
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: none
    show-sql : true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

#配置sql参数打印
logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
upload-url: 127.0.0.1