server:
  port : 8443
spring:
  datasource:
    url: jdbc:mysql://119.29.79.210:3306/blog?characterEncoding=UTF-8&useSSL=false
    username: root
    password: redhat
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql : true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
